// Generated by LiveScript 1.2.0
var path, nar, program, ref$, echo, exit, exists, isFile, toKb, get;
path = require('path');
nar = require('../nar');
program = require('commander');
ref$ = require('../utils'), echo = ref$.echo, exit = ref$.exit, exists = ref$.exists, isFile = ref$.isFile, toKb = ref$.toKb;
program.command('get <url>').description('\n  Download remote archive').usage('[url] [options]').option('-o, --output <path>', 'Output directory. Default to current directory').option('--user <user>', 'HTTP autenticantion user').option('--password <password>', 'HTTP user password').option('--proxy <url>', 'URL proxy to use').option('--timeout <number>', 'HTTP request timeout').option('--strict-ssl', 'Enable strict SSL').option('-d, --debug', 'Enable debug mode. More information will be shown').option('-v, --verbose', 'Enable verbose mode. A lot of information will be shown').on('--help', function(){
  return echo('  Usage examples:\n\n    $ nar get\n    $ nar get app.nar\n    $ nar get app.nar -o some/dir\n    $ nar get app.nar --debug\n    $ nar get http://server.net/app-0.1.0.nar\n\t');
}).action(function(){
  return get.apply(this, arguments);
});
get = function(archive, options){
  var debug, verbose, output, user, password, proxy, opts, onStart, onError, onEntry, onArchive, onEnd, extract, e;
  debug = options.debug, verbose = options.verbose, output = options.output, user = options.user, password = options.password, proxy = options.proxy;
  opts = {
    path: addExtension(
    archive),
    dest: output
  };
  onStart = function(){
    return echo(
    "Reading archive...");
  };
  onError = function(err, code){
    if (err) {
      echo(
      ("Error: " + (err.message || err)).red);
    }
    if (debug && err.stack) {
      echo(
      err.stack);
    }
    return exit(
    code || 1)();
  };
  onEntry = function(it){
    return echo(
    "Extract [".green + (toKb(
    it.size) + " KB").cyan + ("] " + (it.path || '')).green);
  };
  onArchive = function(it){
    if (!(debug && verbose)) {
      return echo(
      "Extracting [" + it.type.cyan + "] " + (it.name || ''));
    }
  };
  onEnd = function(it){
    echo(
    "Extracted in: " + it.dest);
    return exit(0);
  };
  extract = function(){
    var installer;
    installer = nar.install(opts).on('start', onStart).on('archive', onArchive).on('error', onError).on('end', onEnd);
    if (debug || verbose) {
      return installer.on('entry', onEntry);
    }
  };
  try {
    return extract();
  } catch (e$) {
    e = e$;
    return onError(
    "Cannot extract the archive: " + e.message);
  }
};
