// Generated by LiveScript 1.2.0
var path, nar, Table, program, ref$, echo, exit, exists, isFile, addExtension, toKb, archiveName, list, mapEntry;
path = require('path');
nar = require('../nar');
Table = require('cli-table');
program = require('commander');
ref$ = require('../utils'), echo = ref$.echo, exit = ref$.exit, exists = ref$.exists, isFile = ref$.isFile, addExtension = ref$.addExtension, toKb = ref$.toKb, archiveName = ref$.archiveName;
program.command('list <archive>').description('\n  List archive files').usage('[archive] [options]').option('-d, --debug', 'Enable debud mode. More information will be shown').option('--no-table', 'Disable table format output').on('--help', function(){
  return echo('  Usage examples:\n\n    $ nar list app.nar\n    $ nar list app.nar --no-table\n\t');
}).action(function(){
  return list.apply(this, arguments);
});
list = function(archive, options){
  var debug, table, tableList, opts, onError, onInfo, onEntry, onEnd, list, e;
  debug = options.debug, table = options.table;
  tableList = new Table({
    head: ['Name', 'Destination', 'Size', 'Type']
  });
  opts = {
    path: addExtension(
    archive)
  };
  onError = function(it){
    if (it) {
      echo(
      ("Error: " + (it.message || it)).red);
    }
    if (debug && it.stack) {
      echo(
      it.stack);
    }
    return exit(1);
  };
  onInfo = function(it){
    return echo(
    "Package: " + archiveName(
    it));
  };
  onEntry = function(it){
    if (table) {
      return tableList.push(
      mapEntry(
      it));
    } else {
      return echo(
      path.join(it.dest, it.archive) + (" (" + toKb(
      it.size) + " KB)").cyan);
    }
  };
  onEnd = function(){
    if (table) {
      echo(
      tableList.toString());
    }
    return exit(0);
  };
  list = function(){
    if (!isFile(
    opts.path)) {
      exit(1)(
      "The given path is not a file");
    }
    return nar.list(opts).on('error', onError).on('info', onInfo).on('entry', onEntry).on('end', onEnd);
  };
  try {
    return list();
  } catch (e$) {
    e = e$;
    return onError(
    e);
  }
};
mapEntry = function(it){
  if (it) {
    return [
      path.basename(it.archive, '.tar'), it.dest, toKb(
      it.size) + ' KB', it.type
    ];
  }
};
